version: "3"

volumes:
  postgres_data:

services:
  postgres_db:
    image: postgres:12
    container_name: "postgres_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpw
  spring_app:
    image: spring_img:latest
    container_name: "springboot_app"
    ports:
      - "8080:8080"