version: "3"

volumes:
  postgres_data:

services:
  postgres_db:
    image: postgres:12
    container_name: "postgres_BusDb"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpw
